Portalnetwork test coverage
ethereumjs/ultralight pull request #339
Opened 2022-08-12 20:31 UTC by ScottyPoi

Adds to integration test.

2022-08-14 19:05 UTC, ScottyPoi commented
Integration test building revealed a bug in uTP protocol during FOUNDCONTENT requests where ContentWriter would skip the first chunk of data when streaming data packets.

Problem involved when and how seqNr's are set, and read by the writer / socket / packet creator.  
Though I did find the problem and fix it, I feel that there may be a better way to approach this part of the uTP protocol where we increment seqNr's and ackNr's.

Will think on this and propose something in an issue.

2022-08-14 22:05 UTC, ScottyPoi reviewed
@acolytec3, I am still writing integration tests, but I recommend merging this whenever you get a chance to look it over, as it does include some bug fixes as well.

2022-08-14 22:05 UTC, ScottyPoi commented on packages/portalnetwork/src/subprotocols/history/history.ts
> +      if (this.gossipQueue.length >= 26) {
we could create a way to configure this number to anything between 1 and 26, or even dynamically change the number based on traffic or something.
for now, I set it to MAX (26) for the sake of performance.  Larger offers = fewer handshakes.

2022-08-15 16:02 UTC, ScottyPoi commented
added a test for eth_getBlockByNumber 
constraints of the test setup restrict it to blocks within the current epoch of a received accumulator snapshot, for now.

2022-08-15 18:43 UTC, acolytec3 requested changes
This generally looks good but I don't love the idea of `getBlockByNumber` throwing.  Would prefer to handle as just returning undefined.  Also, can you remove commented out code that is duplicated by your fixes? I'm going to do some more indepth testing from browser client this afternoon but looks great overall.

2022-08-15 18:43 UTC, acolytec3 commented on packages/portalnetwork/src/subprotocols/history/history.ts
> +      throw new Error(`Blockhash index lookup not implemented`)
I'm not sure I like the idea of throwing here.  It's not an error if we don't find the block or if the number is too high for the accumulator. I think we should just return undefined.

2022-08-15 19:14 UTC, ScottyPoi commented
Made some edits to enable a test for eth_getBlockByNumber with a historical epoch lookup involved.  
There's some weirdness going on in PortalNetworkUtp._handleFinPacket()  when the content is an epoch accumulator, where the contentKey stored in the utp request is undefined.  Since it is possible to rehash the accumulator to get the proper contentID, the methods work anyway, but it is still an unsolved mystery to me.

2022-08-15 20:00 UTC, acolytec3 approved these changes

2022-08-15 20:01 UTC, merged